## **Flights Information during COVID 19**

---
Use Case: User looking for information on his upcoming travel, say travel to From India to Qatar. 
  * What we are trying to achieve: 
    * How safe is to travel to Qatar?  -- save index 0 to 10
     0 - safe
     10 - not safe
    * How the current status in India going to affect him/her?
    * Is there any airline available for this route?


INDIA - 7
QATAR - 8


INDIA - 3
QATAR - 7 ( AIRLINE Available)

not safe,  Quartine --

INDIA - 7 
QATAR - 3

flight accept
steps





  * How we are going to achieve:
    * NLP
    * Prediction
    * Data Analysis

In [0]:
# Import libraries

import pandas as pd
from datetime import date
import sys
import plotly.graph_objects as go
pd.set_option('display.max_colwidth',500)

from io import BytesIO

import requests

from ipywidgets import TwoByTwoLayout,IntText,Layout,jslink,Text

In [0]:
r = requests.get('https://docs.google.com/spreadsheets/d/e/2PACX-1vTxATUFm0tR6Vqq-UAOuqQ-BoQDvYYEe-BmJ20s50yBKDHEifGofP2P1LJ4jWFIu0Pb_4kRhQeyhHmn/pub?gid=0&single=true&output=csv')
data = r.content

flight_info_Coun = pd.read_csv(BytesIO(data),parse_dates=['published'])
flight_info_Coun.rename(columns={'adm0_name': 'country'}, inplace=True)
flight_info_Coun.head()

         country  ... ObjectId
0          Abyei  ...        1
1    Afghanistan  ...        2
2       Akrotiri  ...        3
3     Aksai Chin  ...        4
4  Åland Islands  ...        5

[5 rows x 11 columns]

In [0]:
r = requests.get('https://docs.google.com/spreadsheets/d/e/2PACX-1vTxATUFm0tR6Vqq-UAOuqQ-BoQDvYYEe-BmJ20s50yBKDHEifGofP2P1LJ4jWFIu0Pb_4kRhQeyhHmn/pub?gid=646351539&single=true&output=csv')
data = r.content

flight_info_airline = pd.read_csv(BytesIO(data),parse_dates=['published'])
flight_info_airline.rename(columns={'adm0_name': 'country'}, inplace=True)
flight_info_airline.head()

         country      iso3          X  ...  optional2 optional3 ObjectId
0          Abyei  SDN, SSD  28.415755  ...        NaN       NaN        1
1    Afghanistan       AFG  66.026881  ...        NaN       NaN        2
2     Aksai Chin  AKS, CHN  79.132432  ...        NaN       NaN        3
3  Åland Islands       ALA  19.809460  ...        NaN       NaN        4
4        Albania       ALB  20.066643  ...        NaN       NaN        5

[5 rows x 12 columns]

Data Preprocessing

In [0]:
flight_info_airline["country"]= flight_info_airline["country"].str.replace("'"," ")
flight_info_Coun["country"]= flight_info_Coun["country"].str.replace("'"," ")

In [0]:

#@title Select a Country from the list
country_list = flight_info_Coun["country"].unique().tolist()
country_list.sort()
from_country = "India" #@param ['Abyei','Afghanistan','Akrotiri','Aksai Chin','Albania','Algeria','American Samoa','Andorra','Angola','Anguilla','Antarctica','Antigua and Barbuda','Argentina','Armenia','Aruba','Arunachal Pradesh','Ashmore and Cartier Islands','Australia','Austria','Azerbaijan','Azores Islands','Bahamas','Bahrain','Baker Island','Bangladesh','Barbados','Bassas da India','Belarus','Belgium','Belize','Benin','Bermuda','Bhutan','Bi r Tawīl','Bird Island','Bolivia','Bonaire','Bosnia and Herzegovina','Botswana','Bouvet Island','Brazil','British Virgin Islands','Brunei Darussalam','Bulgaria','Burkina Faso','Burundi','Cambodia','Cameroon','Canada','Canary Islands','Cape Verde','Cayman Islands','Central African Republic','Chad','Chagos Archipelagio','Chile','China','China/India','Christmas Island','Clipperton Island','Cocos (Keeling) Islands','Colombia','Comoros','Congo','Cook Islands','Costa Rica','Croatia','Cuba','Curaçao','Cyprus','Czechia','Côte d Ivoire','Dekelia','Democratic People s Republic of Korea','Democratic Republic of the Congo','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Europa Island','European Union','Falkland Islands (Malvinas)','Faroe Islands','Fiji','Finland','France','French Guiana','French Polynesia','French Southern Territories','Gabon','Gambia','Gaza','Georgia','Germany','Ghana','Gibraltar','Glorioso Islands','Greece','Greenland','Grenada','Guadeloupe','Guam','Guatemala','Guernsey','Guinea','Guinea-Bissau','Guyana','Haiti','Hala ib Triangle','Heard Island and McDonald Islands','Holy See','Honduras','Hong Kong','Howland Island','Hungary','Iceland','Ilemi Triangle','India','Indonesia','Iran (Islamic Republic of)','Iraq','Ireland','Isle of Man','Israel','Italy','Jamaica','Jammu and Kashmir','Japan','Jarvis Island','Jersey','Johnston Atoll','Jordan','Juan de Nova Island','Kazakhstan','Kenya','Kingman Reef','Kiribati','Kosovo','Kuril Islands','Kuwait','Kyrgyzstan','Lao People s Democratic Republic','Latvia','Lebanon','Lesotho','Liancourt Rock','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Macao','Madagascar','Madeira Islands','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Martinique','Mauritania','Mauritius','Mayotte','Mexico','Micronesia (Federated States of)','Midway Island','Monaco','Mongolia','Montenegro','Montserrat','Morocco','Mozambique','Myanmar','Namibia','Nauru','Navassa Island','Nepal','Netherlands','New Caledonia','New Zealand','Nicaragua','Niger','Nigeria','Niue','Norfolk Island','North Macedonia','Northern Mariana Islands','Norway','Oman','Pakistan','Palau','Palmyra Atoll','Panama','Papua New Guinea','Paracel Islands','Paraguay','Peru','Philippines','Pitcairn','Poland','Portugal','Puerto Rico','Qatar','Republic of Korea','Republic of Moldova','Romania','Russian Federation','Rwanda','Réunion','Saba','Saint Barthélemy','Saint Helena','Saint Kitts and Nevis','Saint Lucia','Saint Martin','Saint Pierre et Miquelon','Saint Vincent and the Grenadines','Samoa','San Marino','Sao Tome and Principe','Saudi Arabia','Scarborough Reef','Senegal','Senkaku Islands','Serbia','Seychelles','Sierra Leone','Singapore','Sint Eustatius','Sint Maarten','Slovakia','Slovenia','Solomon Islands','Somalia','South Africa','South Georgia and the South Sandwich Islands','South Sudan','Sovereignty unsettled','Spain','Spratly Islands','Sri Lanka','Sudan','Suriname','Svalbard and Jan Mayen Islands','Sweden','Switzerland','Syrian Arab Republic','Tadjikistan','Taiwan','Thailand','Timor-Leste','Togo','Tokelau','Tonga','Trinidad and Tobago','Tromelin Island','Tunisia','Turkey','Turkmenistan','Turks and Caicos Islands','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom of Great Britain & Northern Ireland','United Republic of Tanzania','United States Virgin Islands','United States of America','Uruguay','Uzbekistan','Vanuatu','Venezuela','Viet Nam','Wake Island','Wallis and Futuna','West Bank','Western Sahara','Yemen','Zambia','Zimbabwe','Åland Islands']

to_country = "Qatar" #@param ['Abyei','Afghanistan','Akrotiri','Aksai Chin','Albania','Algeria','American Samoa','Andorra','Angola','Anguilla','Antarctica','Antigua and Barbuda','Argentina','Armenia','Aruba','Arunachal Pradesh','Ashmore and Cartier Islands','Australia','Austria','Azerbaijan','Azores Islands','Bahamas','Bahrain','Baker Island','Bangladesh','Barbados','Bassas da India','Belarus','Belgium','Belize','Benin','Bermuda','Bhutan','Bi r Tawīl','Bird Island','Bolivia','Bonaire','Bosnia and Herzegovina','Botswana','Bouvet Island','Brazil','British Virgin Islands','Brunei Darussalam','Bulgaria','Burkina Faso','Burundi','Cambodia','Cameroon','Canada','Canary Islands','Cape Verde','Cayman Islands','Central African Republic','Chad','Chagos Archipelagio','Chile','China','China/India','Christmas Island','Clipperton Island','Cocos (Keeling) Islands','Colombia','Comoros','Congo','Cook Islands','Costa Rica','Croatia','Cuba','Curaçao','Cyprus','Czechia','Côte d Ivoire','Dekelia','Democratic People s Republic of Korea','Democratic Republic of the Congo','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Europa Island','European Union','Falkland Islands (Malvinas)','Faroe Islands','Fiji','Finland','France','French Guiana','French Polynesia','French Southern Territories','Gabon','Gambia','Gaza','Georgia','Germany','Ghana','Gibraltar','Glorioso Islands','Greece','Greenland','Grenada','Guadeloupe','Guam','Guatemala','Guernsey','Guinea','Guinea-Bissau','Guyana','Haiti','Hala ib Triangle','Heard Island and McDonald Islands','Holy See','Honduras','Hong Kong','Howland Island','Hungary','Iceland','Ilemi Triangle','India','Indonesia','Iran (Islamic Republic of)','Iraq','Ireland','Isle of Man','Israel','Italy','Jamaica','Jammu and Kashmir','Japan','Jarvis Island','Jersey','Johnston Atoll','Jordan','Juan de Nova Island','Kazakhstan','Kenya','Kingman Reef','Kiribati','Kosovo','Kuril Islands','Kuwait','Kyrgyzstan','Lao People s Democratic Republic','Latvia','Lebanon','Lesotho','Liancourt Rock','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Macao','Madagascar','Madeira Islands','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Martinique','Mauritania','Mauritius','Mayotte','Mexico','Micronesia (Federated States of)','Midway Island','Monaco','Mongolia','Montenegro','Montserrat','Morocco','Mozambique','Myanmar','Namibia','Nauru','Navassa Island','Nepal','Netherlands','New Caledonia','New Zealand','Nicaragua','Niger','Nigeria','Niue','Norfolk Island','North Macedonia','Northern Mariana Islands','Norway','Oman','Pakistan','Palau','Palmyra Atoll','Panama','Papua New Guinea','Paracel Islands','Paraguay','Peru','Philippines','Pitcairn','Poland','Portugal','Puerto Rico','Qatar','Republic of Korea','Republic of Moldova','Romania','Russian Federation','Rwanda','Réunion','Saba','Saint Barthélemy','Saint Helena','Saint Kitts and Nevis','Saint Lucia','Saint Martin','Saint Pierre et Miquelon','Saint Vincent and the Grenadines','Samoa','San Marino','Sao Tome and Principe','Saudi Arabia','Scarborough Reef','Senegal','Senkaku Islands','Serbia','Seychelles','Sierra Leone','Singapore','Sint Eustatius','Sint Maarten','Slovakia','Slovenia','Solomon Islands','Somalia','South Africa','South Georgia and the South Sandwich Islands','South Sudan','Sovereignty unsettled','Spain','Spratly Islands','Sri Lanka','Sudan','Suriname','Svalbard and Jan Mayen Islands','Sweden','Switzerland','Syrian Arab Republic','Tadjikistan','Taiwan','Thailand','Timor-Leste','Togo','Tokelau','Tonga','Trinidad and Tobago','Tromelin Island','Tunisia','Turkey','Turkmenistan','Turks and Caicos Islands','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom of Great Britain & Northern Ireland','United Republic of Tanzania','United States Virgin Islands','United States of America','Uruguay','Uzbekistan','Vanuatu','Venezuela','Viet Nam','Wake Island','Wallis and Futuna','West Bank','Western Sahara','Yemen','Zambia','Zimbabwe','Åland Islands']

In [0]:
#print(to_country)

#from_country

to_df = flight_info_airline[flight_info_airline["country"]== to_country]
from_df =  flight_info_airline[flight_info_airline["country"]== from_country]

In [0]:
full_url ="https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.xlsx"

cases_df = pd.read_excel(full_url,sep=" ")
cases_df.head(1)

      dateRep  day  month  ...  countryterritoryCode  popData2018  continentExp
0  16/05/2020   16      5  ...                   AFG   37172386.0          Asia

[1 rows x 11 columns]

In [0]:
to_country1 = to_country.replace(" ","_")
from_country1 = from_country.replace(" ","_")
from_country1

'India'

In [0]:
to_case = cases_df[cases_df['countriesAndTerritories']== to_country1]
from_case = cases_df[cases_df['countriesAndTerritories']== from_country1]

In [0]:
to_case

          dateRep  day  month  ...  countryterritoryCode  popData2018  continentExp
13082  16/05/2020   16      5  ...                   QAT    2781677.0          Asia
13083  15/05/2020   15      5  ...                   QAT    2781677.0          Asia
13084  14/05/2020   14      5  ...                   QAT    2781677.0          Asia
13085  13/05/2020   13      5  ...                   QAT    2781677.0          Asia
13086  12/05/2020   12      5  ...                   QAT    2781677.0          Asia
...           ...  ...    ...  ...                   ...          ...           ...
13211  04/01/2020    4      1  ...                   QAT    2781677.0          Asia
13212  03/01/2020    3      1  ...                   QAT    2781677.0          Asia
13213  02/01/2020    2      1  ...                   QAT    2781677.0          Asia
13214  01/01/2020    1      1  ...                   QAT    2781677.0          Asia
13215  31/12/2019   31     12  ...                   QAT    2781677.0          Asia

[134 rows x 11 columns]

In [0]:
from_case

         dateRep  day  month  ...  countryterritoryCode   popData2018  continentExp
7439  16/05/2020   16      5  ...                   IND  1.352617e+09          Asia
7440  15/05/2020   15      5  ...                   IND  1.352617e+09          Asia
7441  14/05/2020   14      5  ...                   IND  1.352617e+09          Asia
7442  13/05/2020   13      5  ...                   IND  1.352617e+09          Asia
7443  12/05/2020   12      5  ...                   IND  1.352617e+09          Asia
...          ...  ...    ...  ...                   ...           ...           ...
7571  04/01/2020    4      1  ...                   IND  1.352617e+09          Asia
7572  03/01/2020    3      1  ...                   IND  1.352617e+09          Asia
7573  02/01/2020    2      1  ...                   IND  1.352617e+09          Asia
7574  01/01/2020    1      1  ...                   IND  1.352617e+09          Asia
7575  31/12/2019   31     12  ...                   IND  1.352617e+09          Asia

[137 rows x 11 columns]